# -*- coding: utf-8 -*-
#
# flask_mab documentation build configuration file, created by
# sphinx-quickstart on Mon Oct 28 17:57:57 2013.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.
from sphinx_pyproject import SphinxConfig

config = SphinxConfig("../pyproject.toml", globalns=globals())

html_theme_options = {
    'index_logo': 'flask_mab.png',
    'index_logo_height': "200px",
    'github_fork': 'deacondesperado/flask_mab',
}
