name: build-test 
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: "build-test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '>=3.10' 
      - name: Set up build deps
        run: python -m pip install --upgrade build 
      - name: Install dependencies
        run: python -m pip install '.[dev]'
      - name: Run tests
        run: tox 
      - name: Build dist
        run: python -m build . 
      - name: Build docs
        uses: ammaraskar/sphinx-action@0.4
        with:
          pre-build-command: python -m pip install '.[dev]'
          docs-folder: "docs/"
          build-command: sphinx-build -b html . _build

